import type { ProviderDefinition } from './types/provider.js';

export const BUILT_IN_PROVIDERS: ProviderDefinition[] = [
  {
    id: 'anthropic',
    display_name: 'Anthropic (Claude)',
    sdk: 'anthropic',
    api_key_env: 'ANTHROPIC_API_KEY',
    requires_key: true,
    default_model: 'claude-haiku-4-5',
    suggested_models: ['claude-haiku-4-5', 'claude-sonnet-4-5', 'claude-opus-4-5'],
    notes: 'Recommended default. Best classification accuracy.',
  },
  {
    id: 'openai',
    display_name: 'OpenAI (GPT)',
    sdk: 'openai-compatible',
    api_key_env: 'OPENAI_API_KEY',
    requires_key: true,
    default_model: 'gpt-4o-mini',
    suggested_models: ['gpt-4o-mini', 'gpt-4o', 'gpt-4-turbo'],
  },
  {
    id: 'groq',
    display_name: 'Groq',
    sdk: 'openai-compatible',
    base_url: 'https://api.groq.com/openai/v1',
    api_key_env: 'GROQ_API_KEY',
    requires_key: true,
    default_model: 'llama-3.3-70b-versatile',
    suggested_models: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768'],
    notes: 'Extremely fast inference. Good cost/performance ratio.',
  },
  {
    id: 'deepseek',
    display_name: 'DeepSeek',
    sdk: 'openai-compatible',
    base_url: 'https://api.deepseek.com/v1',
    api_key_env: 'DEEPSEEK_API_KEY',
    requires_key: true,
    default_model: 'deepseek-chat',
    suggested_models: ['deepseek-chat', 'deepseek-reasoner'],
    notes: 'Very low cost. Strong for structured output tasks.',
  },
  {
    id: 'kimi',
    display_name: 'Kimi (Moonshot AI)',
    sdk: 'openai-compatible',
    base_url: 'https://api.moonshot.cn/v1',
    api_key_env: 'MOONSHOT_API_KEY',
    requires_key: true,
    default_model: 'moonshot-v1-8k',
    suggested_models: ['moonshot-v1-8k', 'moonshot-v1-32k', 'moonshot-v1-128k'],
  },
  {
    id: 'mistral',
    display_name: 'Mistral AI',
    sdk: 'openai-compatible',
    base_url: 'https://api.mistral.ai/v1',
    api_key_env: 'MISTRAL_API_KEY',
    requires_key: true,
    default_model: 'mistral-small-latest',
    suggested_models: ['mistral-small-latest', 'mistral-medium-latest', 'mistral-large-latest'],
  },
  {
    id: 'together',
    display_name: 'Together AI',
    sdk: 'openai-compatible',
    base_url: 'https://api.together.xyz/v1',
    api_key_env: 'TOGETHER_API_KEY',
    requires_key: true,
    default_model: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    suggested_models: [
      'meta-llama/Llama-3.3-70B-Instruct-Turbo',
      'mistralai/Mixtral-8x7B-Instruct-v0.1',
    ],
    notes: 'Access to many open-source models.',
  },
  {
    id: 'perplexity',
    display_name: 'Perplexity',
    sdk: 'openai-compatible',
    base_url: 'https://api.perplexity.ai',
    api_key_env: 'PERPLEXITY_API_KEY',
    requires_key: true,
    default_model: 'llama-3.1-sonar-small-128k-chat',
    suggested_models: [
      'llama-3.1-sonar-small-128k-chat',
      'llama-3.1-sonar-large-128k-chat',
    ],
  },
  {
    id: 'ollama',
    display_name: 'Ollama (local)',
    sdk: 'openai-compatible',
    base_url: 'http://localhost:11434/v1',
    api_key_env: 'OLLAMA_API_KEY',
    requires_key: false,
    default_model: 'llama3.2',
    suggested_models: ['llama3.2', 'llama3.1', 'mistral', 'phi3', 'gemma2'],
    notes: 'Runs locally. No API key or cost. Requires Ollama installed: https://ollama.com',
  },
];
